import React from "react";
import { Mail } from "lucide-react";

export default function TermsPage() {
  return (
    <main className="bg-[#f7f7f8] min-h-screen pt-[98px] pb-16">
      {/* HERO/BANNER */}
      <section className="relative w-full">
        <div className="bg-gradient-to-br from-[#e5e8fd] via-[#f2f2f8] to-[#fff] shadow-sm rounded-b-3xl px-6 pt-14 pb-10 flex flex-col items-center justify-center text-center">
          <h1 className="text-4xl md:text-5xl font-bold text-indigo-900 mb-4 drop-shadow">
            Terms &amp; Conditions
          </h1>
          <p className="text-lg md:text-xl text-gray-700 max-w-2xl mb-2">
            Rules, rights, and responsibilities for using the official website of the Somali Data Protection Authority (DPA).
          </p>
        </div>
      </section>

      {/* MAIN CONTENT */}
      <section className="max-w-3xl mx-auto bg-white rounded-2xl border border-gray-200 shadow-lg px-6 md:px-10 py-10 mt-[-40px]">
        <p className="mb-4 text-gray-600 italic text-sm">
          (This is an electronic record generated by a computer system and does not require any physical or digital signatures. It is published in accordance with applicable laws and principles of Somalia.)
        </p>
        <h2 className="text-2xl font-bold mb-2 text-indigo-800">1. Ownership and Copyright</h2>
        <p className="mb-5 text-gray-800">
          Unless otherwise stated, all content on this website—including text, graphics, logos, images, downloadable materials, and software—is the property of the Data Protection Authority of Somalia. All content is protected by copyright and intellectual property laws. You may not reproduce, republish, or distribute any material from this website without the express prior written permission of the DPA.
        </p>

        <h2 className="text-2xl font-bold mb-2 text-indigo-800">2. Acceptance of Terms</h2>
        <p className="mb-5 text-gray-800">
          By accessing and using this website, you acknowledge that you have read, understood, and agree to be bound by these Terms and Conditions. If you do not agree with any part of these terms, discontinue use of the website immediately.
        </p>

        <h2 className="text-2xl font-bold mb-2 text-indigo-800">3. Definitions</h2>
        <ul className="mb-5 pl-6 list-disc text-gray-800">
          <li><b>“User,” “You,” or “Your”</b> refers to any person who accesses or uses the website.</li>
          <li><b>“DPA,” “The Authority,” “We,” “Our,” or “Us”</b> refers to the Data Protection Authority of Somalia.</li>
          <li><b>“Party” or “Parties”</b> refers to both the User and the DPA, or either one individually, as appropriate.</li>
        </ul>

        <h2 className="text-2xl font-bold mb-2 text-indigo-800">4. External Links</h2>
        <p className="mb-5 text-gray-800">
          This website may contain links to other websites or applications managed by third parties. These links are provided for informational purposes only. The DPA does not control or endorse any such third-party websites and is not responsible for their content, accuracy, or data practices. Users access third-party websites at their own risk.
        </p>

        <h2 className="text-2xl font-bold mb-2 text-indigo-800">5. Limitation of Liability</h2>
        <p className="mb-5 text-gray-800">
          To the fullest extent permitted by applicable law, the DPA shall not be liable for any direct, indirect, incidental, consequential, or punitive damages arising from your access to or use of the website. This includes, but is not limited to, damages for errors, omissions, interruptions, inaccuracies, or loss of data.
        </p>

        <h2 className="text-2xl font-bold mb-2 text-indigo-800">6. User Responsibilities</h2>
        <ul className="mb-5 pl-6 list-disc text-gray-800">
          <li>Do not use the website for any unlawful purpose or in violation of any applicable law or regulation.</li>
          <li>Do not attempt to gain unauthorized access to any part of the website, server, or network.</li>
          <li>Do not introduce viruses, malware, or other harmful code.</li>
          <li>Do not interfere with the website’s operation or other users’ access.</li>
        </ul>

        <h2 className="text-2xl font-bold mb-2 text-indigo-800">7. Termination of Access</h2>
        <p className="mb-5 text-gray-800">
          We reserve the right to suspend or terminate your access to the website without notice for conduct that violates these terms, applicable laws, or is harmful to other users or the DPA.
        </p>

        <h2 className="text-2xl font-bold mb-2 text-indigo-800">8. Governing Law</h2>
        <p className="mb-5 text-gray-800">
          These Terms and Conditions are governed by the laws of the Federal Republic of Somalia. Any disputes shall be subject to the exclusive jurisdiction of the competent courts of Somalia.
        </p>

        <h2 className="text-2xl font-bold mb-2 text-indigo-800">9. Changes to Terms</h2>
        <p className="mb-5 text-gray-800">
          The DPA reserves the right to update or revise these Terms and Conditions at any time. Changes are effective upon posting on this page. Review this page periodically for updates.
        </p>

        <h2 className="text-2xl font-bold mb-2 text-indigo-800">Contact Us</h2>
        <div className="flex items-center gap-2 mb-1">
          <Mail className="w-5 h-5 text-blue-500" />
          <a href="mailto:info@dpa.gov.so" className="underline text-blue-800">
            info@dpa.gov.so
          </a>
        </div>
        <a
          href="https://dpa.gov.so"
          target="_blank"
          rel="noopener"
          className="underline text-blue-800"
        >
          https://dpa.gov.so
        </a>
      </section>
    </main>
  );
}
